# Generated by Django 4.0.4 on 2022-05-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten_url', '0003_shorturlmodel_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturlmodel',
            name='short_id',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
